### ISSUE TITLE
Report and Screenshots generated in NPM folder

### ISSUE THREAD

**Issue by savannahar68** [savannahar68/web-review#1]
Reports and Screenshots are generated in node_modules/web-review/src folder
It should be created in the folder from where the package is used

Fixes - Path needs to be changed while saving the results

**Comment by vasusharma7** [comment]
Reports were already produced in the same directory from where it was called.. Have implemented the same for screenshots also. Please have a look

**Comment by savannahar68** [comment]
@vasusharma7 No,

Try this: 
in the web-review repo - type npm link
This will link your package as global package

Now create a new folder web-review-test :
Do 
npm init -y
npm link web-review // this will take package from systems global npm repo

Now create a new file and use web-review module as 
const webreview = require('web-review)
webreview(https://github.com)

When you run this file the output generated are in node_modules folder and not in the folder from where this module was called.

**Comment by vasusharma7** [comment]
Ok @savannahar68 I will check it out soon

**Comment by savannahar68** [comment]
Fixed in latest commit!
