### ISSUE TITLE
Combine results - Screenshots and Audit Report 

### ISSUE THREAD

**Issue by savannahar68** [savannahar68/web-review#3]
Right now, both the results are generated separately, combine them as a single unit into 
HTML as well as PDF
(HTML => PDF converter)

**Comment by vasusharma7** [comment]
For combining the audit report with the screenshots, the screenshots will have to be inserted in html which doesn't look so easy as the html is generated with ReportGenerator. (though it is doable). 
Will give a shot.
Any advises/ suggestions as to how to proceed.

**Comment by savannahar68** [comment]
Added in commit d9f9c68fd0306396dd50c885bebf87b74d79af95
